// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GtkControl {
    
    
    public partial class kk {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GtkControl.kk
            Stetic.BinContainer.Attach(this);
            this.Name = "GtkControl.kk";
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
