// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GtkControl {
    
    
    public partial class MVPanel {
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.Fixed fixed1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GtkControl.MVPanel
            Stetic.BinContainer.Attach(this);
            this.Name = "GtkControl.MVPanel";
            // Container child GtkControl.MVPanel.Gtk.Container+ContainerChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            Gtk.Viewport w1 = new Gtk.Viewport();
            w1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.Events = ((Gdk.EventMask)(252));
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            w1.Add(this.fixed1);
            this.scrolledwindow1.Add(w1);
            this.Add(this.scrolledwindow1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.fixed1.MotionNotifyEvent += new Gtk.MotionNotifyEventHandler(this.OnFixed1MotionNotifyEvent);
        }
    }
}
